<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('oficina', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->increments('id');
            $table->string('entidad');
            $table->string('unidad');
            $table->integer('idestablecimiento')->unsigned();
            $table->integer('codofic');
            $table->string('nomofic');
            $table->string('observ')->nullable();
            $table->string('feult')->nullable();
            $table->string('usuar');
            $table->string('api_estado');
            $table->integer('estadodbf')->default(0);
            $table->foreign('idestablecimiento')->references('id')->on('establecimientos');
            $table->timestamps();
        });
       DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>1,'nomofic'=>'DIRECCION NACIONAL DE SALUD Y BIENESTAR SOCIAL','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>2,'nomofic'=>'SECRETARIA DIR NAL DE SALUD Y BIENESTAR SOCIAL','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>3,'nomofic'=>'AYUDANTIA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>4,'nomofic'=>'ARCHIVO CENTRAL','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>5,'nomofic'=>'ASESORIA JURIDICA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>6,'nomofic'=>'RELACIONES PUBLICAS','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>7,'nomofic'=>'CONSEJO TECNICO DE ASESORIA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>8,'nomofic'=>'DEPARTAMENTO NACIONAL DE SALUD','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>9,'nomofic'=>'SECRETARIA DEPTO NAL DE SALUD','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>10,'nomofic'=>'COMITÉ DE ASESORAMIENTO TECNICO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>11,'nomofic'=>'DIVISION ADMINISTRACION EN SALUD','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>12,'nomofic'=>'SECCION GESTION DE CALIDAD','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>13,'nomofic'=>'SECCION PROM. PREV. Y EDUC EN SALUD','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>14,'nomofic'=>'DEPARTAMENTO NACIONAL DE BIENESTAR SOCIAL','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>15,'nomofic'=>'SECRETARIA DEPTO NAL DE BIENESTAR SOCIAL','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>16,'nomofic'=>'KARDEX Y ARCHIVO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>17,'nomofic'=>'DIVISION SERVICION SOCIAL','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>18,'nomofic'=>'SECC DISPONIBILIDAD LETRA A','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>19,'nomofic'=>'SECC SUBSIDIOS POR INCAPACIDAD TEMPORAL','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>20,'nomofic'=>'SECCION MAUSULEOS','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>21,'nomofic'=>'DIVISION DE TRABAJO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>22,'nomofic'=>'SECC AFILIACION SEGUROS','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>23,'nomofic'=>'DIVISION CENTROS INFANTILES','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>24,'nomofic'=>'SECCION COORD CON RESP DEL AREA SOCIAL','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>25,'nomofic'=>'SECCION SERVICIOS GENERALES','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>26,'nomofic'=>'DEPARTAMENTO NAL DE PSICOLOGIA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>27,'nomofic'=>'SECRETARIA DEPTO NAL DE PSICOLOGIA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>28,'nomofic'=>'GRUPO GEAC','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>29,'nomofic'=>'DIVISION DE PSICOLOGIA CLINICA TERAPEUTICA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>30,'nomofic'=>'SECCION PSICOLOGIA EDUCATIVA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>31,'nomofic'=>'DIVISION DE PSICOLOGIA SOCIAL','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>32,'nomofic'=>'SECCION PSICOLOGIA FORENSE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>33,'nomofic'=>'DEPARTAMENTO NACIONAL DE PERSONAL','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>34,'nomofic'=>'SECRETARIA DEPTO NAL DE PERSONAL','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>35,'nomofic'=>'DIVISION MOV DE PERSONAL','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>36,'nomofic'=>'SECCION ESCALAFON','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>37,'nomofic'=>'DEPARTAMENTO NAL DE PLANEAMIENTO ESTRATEGICO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>38,'nomofic'=>'SECRETARIA NAL DE PLAN ESTRATEGICO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>39,'nomofic'=>'DIVISION PLANEAMIENTO OPERATIVO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>40,'nomofic'=>'SECCION ORG METODOS Y REGLAMENTACION','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>41,'nomofic'=>'DIVISION DE SISTEMAS','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>42,'nomofic'=>'SECCION REDES E INFORMATICA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>43,'nomofic'=>'SECCION ESTADISTICAS','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>44,'nomofic'=>'DEPTO NAL ADMINISTRATIVO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>45,'nomofic'=>'SECRETARIA DEPTO NAL ADMINISTRATIVO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>46,'nomofic'=>'SERVICIOS GENERALES','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>47,'nomofic'=>'DIVISION DE ADQUISICIONES','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>48,'nomofic'=>'SECCION CONTRATACIONES','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>49,'nomofic'=>'DIVISION DE CONTABILIDAD','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>50,'nomofic'=>'SECCION ALMACENES','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>51,'nomofic'=>'SECCION ACTIVOS','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>52,'nomofic'=>'SECCION INGRESOS','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>53,'nomofic'=>'SECCION EGRESOS','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>54,'nomofic'=>'DIVISION PRESUPUESTOS','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>55,'nomofic'=>'SECCION PRESUPUESTOS','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>56,'nomofic'=>'DIVISION TESORERIA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>57,'nomofic'=>'SECCION CREDITOS','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSNAL','idestablecimiento'=>3,'codofic'=>58,'nomofic'=>'SECCION CAJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>125,'nomofic'=>'ADMINISTRATIVA CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>138,'nomofic'=>'ANAPOL CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>95,'nomofic'=>'ANESTESIOLOGIA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>135,'nomofic'=>'ANSSCLAPOL EL ALTO CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>136,'nomofic'=>'ANSSCLAPOL LA PAZ CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>61,'nomofic'=>'ASESORIA JURIDICA DEPTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>116,'nomofic'=>'AUX. ENF CUIDADOS INTENSIVOS HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>112,'nomofic'=>'AUXILIAR DE ENFERMERIA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>167,'nomofic'=>'AUXILIAR DE ENFERMERIA POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>172,'nomofic'=>'AUXILIAR DE ENFERMERIA POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>103,'nomofic'=>'BACTERIOLOGIA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>200,'nomofic'=>'CAJAS CONSULTORES EXTERNOS','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>170,'nomofic'=>'CAJERO POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>83,'nomofic'=>'CARDIOLOGIA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>189,'nomofic'=>'CARDIOLOGIA POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>119,'nomofic'=>'CIRCULANTE HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>140,'nomofic'=>'CIRUGIA CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>88,'nomofic'=>'CIRUGIA GENERAL HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>134,'nomofic'=>'COMADO REG ZONA SUR CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>124,'nomofic'=>'COMITÉ DE ASESORAMIENTO Y GEST. DE CAL CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>77,'nomofic'=>'COMITES DE ASESORAMIENTO Y GESTION DE CALIDAD','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>184,'nomofic'=>'CONSEJO TECNICO POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>168,'nomofic'=>'CONSULT ODONTOLOGICO ANSSCLAPOL POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>198,'nomofic'=>'CONSULTORES EXTERNOS Y OTROS LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>122,'nomofic'=>'DIRECCION CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>1,'nomofic'=>'DIRECCION DEPTAL DE SALUD Y BIENESTAR SOCIAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>75,'nomofic'=>'DIRECCION MEDICA HOSPITAL POLICIAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>173,'nomofic'=>'DIRECCION POLICONSULTORIO DE SALUD ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>146,'nomofic'=>'DIRECCION REGIONAL POLICONSULTORIO DE SALUD EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>156,'nomofic'=>'DIV JEF MEDICA Y GEST DE SALUD POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>65,'nomofic'=>'DIVISION ADMINISTRATIVA DEPTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>149,'nomofic'=>'DIVISION ADMINISTRATIVA POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>176,'nomofic'=>'DIVISION ADMINISTRATIVA POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>63,'nomofic'=>'DIVISION DE PERSONAL DEPTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>183,'nomofic'=>'DIVISION JEFATURA MEDICA POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>137,'nomofic'=>'DP 3 CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>141,'nomofic'=>'ENDODONCIA CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>111,'nomofic'=>'ENF CONSULTORIO EMERGENCIA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>113,'nomofic'=>'ENF CONSULTORIO EXTERNO HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>143,'nomofic'=>'ENFERMERIA CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>166,'nomofic'=>'ENFERMERIA POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>187,'nomofic'=>'ENFERMERIA POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>106,'nomofic'=>'FISIOTERAPEUTA KINESIOLOGO HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>203,'nomofic'=>'FISIOTERAPIA CONSULTORES EXTERNOS','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>163,'nomofic'=>'FISIOTERAPIA POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>195,'nomofic'=>'FISIOTERAPIA POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>80,'nomofic'=>'GASTROENTEROLOGIA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>94,'nomofic'=>'GINECOLOGIA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>160,'nomofic'=>'GINECOLOGIA POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>190,'nomofic'=>'GINECOLOGIA POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>118,'nomofic'=>'INSTRUMENTISTA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>139,'nomofic'=>'INTEGRAL ADULTOS CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>133,'nomofic'=>'JEFATURA ODONTOLOGIA CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>164,'nomofic'=>'LABORATORIO BIOQUIMICO POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>101,'nomofic'=>'LABORATORIO CLINICO HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>144,'nomofic'=>'LABORATORIO DENTAL CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>194,'nomofic'=>'LABORATORIO POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>115,'nomofic'=>'LIC ENF DE CUIDADOS INSTENSIVOS HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>110,'nomofic'=>'LIC ENFERMERA DE PISO HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>199,'nomofic'=>'MEDICINA GENERAL CONSULTORES EXTERNOS','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>171,'nomofic'=>'MEDICINA GENERAL ESBAPOL POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>85,'nomofic'=>'MEDICINA GENERAL HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>157,'nomofic'=>'MEDICINA GENERAL POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>185,'nomofic'=>'MEDICINA GENERAL POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>169,'nomofic'=>'MEDICINA GENERAL TRANSITO POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>196,'nomofic'=>'MEDICINA GRAL COMANDO REG POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>81,'nomofic'=>'MEDICINA INTERNA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>191,'nomofic'=>'MEDICINA POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>96,'nomofic'=>'MEDICO ECOGRAFO HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>97,'nomofic'=>'MEDICO RADIOLOGO HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>89,'nomofic'=>'NEUROCIRUGIA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>186,'nomofic'=>'ODONTOLIGA POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>197,'nomofic'=>'ODONTOLOGIA COMANDO REG POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>158,'nomofic'=>'ODONTOLOGIA POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>142,'nomofic'=>'ODONTOPEDIATRIA CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>202,'nomofic'=>'OFTALMOLOGIA CONSULTORES EXTERNOS','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>90,'nomofic'=>'OFTALMOLOGIA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>201,'nomofic'=>'OTORRINOLARINGOLOGIA CONSULTORES EXTERNOS','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>91,'nomofic'=>'OTORRRINOLARINGOLOGIA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>79,'nomofic'=>'PEDIATRIA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>161,'nomofic'=>'PEDIATRIA POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>93,'nomofic'=>'PROCTOLOGIA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>62,'nomofic'=>'PROMOCION EN SALUD MARKETINF Y RR.P.P. LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>162,'nomofic'=>'PSICOLOGIA CLINICA POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>192,'nomofic'=>'PSICOLOGIA CLINICA POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>86,'nomofic'=>'PSICOLOGIA CLINICA TERAPEUTICA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>82,'nomofic'=>'PSIQUIATRIA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>165,'nomofic'=>'RAYOS X POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>193,'nomofic'=>'RAYOS X POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>120,'nomofic'=>'RECUPERACION Y SUMINISTRO HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>132,'nomofic'=>'SECCION ACTIVOS FIJOS CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>72,'nomofic'=>'SECCION ACTIVOS FIJOS DEPTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>152,'nomofic'=>'SECCION ACTIVOS FIJOS POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>180,'nomofic'=>'SECCION ACTIVOS FIJOS POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>127,'nomofic'=>'SECCION ADMINISION CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>70,'nomofic'=>'SECCION ADMISION DEPTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>178,'nomofic'=>'SECCION ADMISION FIJACION POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>150,'nomofic'=>'SECCION ADMISION POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>130,'nomofic'=>'SECCION ALMACEN CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>68,'nomofic'=>'SECCION ALMACEN DEPTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>177,'nomofic'=>'SECCION ALMACEN POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>154,'nomofic'=>'SECCION ALMACENES POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>74,'nomofic'=>'SECCION ARCHIVO DE KARDEX DEPTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>126,'nomofic'=>'SECCION CAJA CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>67,'nomofic'=>'SECCION CAJA DEPTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>153,'nomofic'=>'SECCION CAJA POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>181,'nomofic'=>'SECCION CAJAS POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>131,'nomofic'=>'SECCION ELECTROMEDICINA CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>128,'nomofic'=>'SECCION ESTADISTICAS CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>73,'nomofic'=>'SECCION ESTADISTICAS DEPTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>151,'nomofic'=>'SECCION ESTADISTICAS POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>179,'nomofic'=>'SECCION ESTADISTICAS POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>66,'nomofic'=>'SECCION INFORMACIONES DEPTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>64,'nomofic'=>'SECCION MOVIMIENTO DE PERSONAL DEPTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>71,'nomofic'=>'SECCION SEGURIDAD DEPTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>129,'nomofic'=>'SECCION SERVICIOS GENERALES CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>155,'nomofic'=>'SECCION SERVICIOS GENERALES POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>182,'nomofic'=>'SECCION SERVICIOS GENERALES POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>69,'nomofic'=>'SECCION SISTEMAS DEPTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>123,'nomofic'=>'SECRETARIA CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>3,'codofic'=>60,'nomofic'=>'SECRETARIA DIR DEPTAL DE SALUD Y BIENESTAR SOCIAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>76,'nomofic'=>'SECRETARIA MEDICA HOSPITAL POLICIAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>147,'nomofic'=>'SECRETARIA POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>174,'nomofic'=>'SECRETARIA POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>100,'nomofic'=>'SECRETARIA SERV DE LAB HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>84,'nomofic'=>'SERVICIO DE EMERGENCIAS HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>108,'nomofic'=>'SERVICIO DE ENFERMERIA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>105,'nomofic'=>'SERVICIO DE FISIOTERAPIA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>99,'nomofic'=>'SERVICIO DE LABORATORIO HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>2,'codofic'=>145,'nomofic'=>'SERVICIO DE RAYOS X CLINICA DENTAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>102,'nomofic'=>'SERVICIO DE TRANSFUCION HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>148,'nomofic'=>'SERVICIO SOCIAL POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>175,'nomofic'=>'SERVICIO SOCIAL POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>121,'nomofic'=>'SERVICIOS GENERALES HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>78,'nomofic'=>'SERVICIOS MEDICOS HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>109,'nomofic'=>'SUPERVISORA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>104,'nomofic'=>'TECNICO DE LABORATORIO CLINICO HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>98,'nomofic'=>'TECNICO RADIOLOGO HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>107,'nomofic'=>'TRABAJO SOCIAL HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>87,'nomofic'=>'TRAUMATOLOGIA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>7,'codofic'=>159,'nomofic'=>'TRAUMATOLOGIA POLICONSULT EL ALTO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>8,'codofic'=>188,'nomofic'=>'TRAUMATOLOGIA POLICONSULT ZONA SUR','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>114,'nomofic'=>'UNIDAD DE CUIDADOS INTENSIVOS HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>117,'nomofic'=>'UNIDAD DE QUIROFNO HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSLPZ','idestablecimiento'=>1,'codofic'=>92,'nomofic'=>'UROLOGIA HOSPITAL LA PAZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>1,'nomofic'=>'DIRECCION DEPTAL DE SALUD Y BIENESTAR SOCIAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>2,'nomofic'=>'SECRETARIA DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>3,'nomofic'=>'UNIDAD JURIDICA DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>4,'nomofic'=>'TRABAJO SOCIAL DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>5,'nomofic'=>'PSICOLOGIA DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>6,'nomofic'=>'DIVISION DE PERSONAL DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>7,'nomofic'=>'MOVIMIENTO DE PERSONAL DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>8,'nomofic'=>'ESTADISTICAS Y ARCHIVO DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>9,'nomofic'=>'DIVISION ADMINISTRATIVA DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>10,'nomofic'=>'SECCION ALMACEN DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>11,'nomofic'=>'SECCION ADMISION FIJACION DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>12,'nomofic'=>'SECCION ESTADISTICAS DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>13,'nomofic'=>'SECCION ACTIVOS FIJOS DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>14,'nomofic'=>'SECCION CAJAS DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>15,'nomofic'=>'SECCION SERVICIOS GENERALES DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>16,'nomofic'=>'DIVISION JEFATURA MEDICA DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>17,'nomofic'=>'COMITÉ DE ASESOR Y GEST DE CALIDAD DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>18,'nomofic'=>'MEDICINA GRAL Y ESPECIALIDADES MEDICAS DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>19,'nomofic'=>'SERVICIO DE DIAGNOSTICO Y TRATAMIENTO DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>20,'nomofic'=>'FISIOTERAPIA DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>21,'nomofic'=>'LABORATORIO DE ANALISIS CLINICO DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>22,'nomofic'=>'RAYOS X DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>23,'nomofic'=>'SERVICIO DE ODONTOLOGIA DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>24,'nomofic'=>'GABINETE MEDICOS DE TRANSITO DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSORU','idestablecimiento'=>38,'codofic'=>25,'nomofic'=>'SERVICIO DE ENFERMERIA DEPTAL ORURO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>1,'nomofic'=>'DIRECCION DEPTAL DE SALUD Y BIENESTAR SOCIAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>2,'nomofic'=>'SECRETARIA DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>3,'nomofic'=>'UNIDAD JURIDICA DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>4,'nomofic'=>'TRABAJO SOCIAL DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>5,'nomofic'=>'PSICOLOGIA DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>6,'nomofic'=>'DIVISION DE PERSONAL DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>7,'nomofic'=>'MOVIMIENTO DE PERSONAL DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>8,'nomofic'=>'ESTADISTICAS Y ARCHIVO DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>9,'nomofic'=>'DIVISION ADMINISTRATIVA DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>10,'nomofic'=>'SECCION ALMACEN DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>11,'nomofic'=>'SECCION ADMISION FIJACION DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>12,'nomofic'=>'SECCION ESTADISTICAS DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>13,'nomofic'=>'SECCION ACTIVOS FIJOS DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>14,'nomofic'=>'SECCION CAJAS DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>15,'nomofic'=>'SECCION SERVICIOS GENERALES DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>16,'nomofic'=>'DIVISION JEFATURA MEDICA DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>17,'nomofic'=>'COMITÉ DE ASESOR Y GEST DE CALIDAD DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>18,'nomofic'=>'MEDICINA GRAL Y ESPECIALIDADES MEDICAS DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>19,'nomofic'=>'SERVICIO DE DIAGNOSTICO Y TRATAMIENTO DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>20,'nomofic'=>'FISIOTERAPIA DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>21,'nomofic'=>'LABORATORIO DE ANALISIS CLINICO DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>22,'nomofic'=>'RAYOS X DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>23,'nomofic'=>'SERVICIO DE ODONTOLOGIA DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>24,'nomofic'=>'GABINETE MEDICOS DE TRANSITO DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPOT','idestablecimiento'=>32,'codofic'=>25,'nomofic'=>'SERVICIO DE ENFERMERIA DEPTAL POTOSI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>1,'nomofic'=>'DIRECCION DEPTAL DE SALUD Y BIENESTAR SOCIAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>2,'nomofic'=>'SECRETARIA DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>3,'nomofic'=>'UNIDAD JURIDICA DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>4,'nomofic'=>'TRABAJO SOCIAL DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>5,'nomofic'=>'PSICOLOGIA DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>6,'nomofic'=>'DIVISION DE PERSONAL DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>7,'nomofic'=>'MOVIMIENTO DE PERSONAL DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>8,'nomofic'=>'ESTADISTICAS Y ARCHIVO DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>9,'nomofic'=>'DIVISION ADMINISTRATIVA DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>10,'nomofic'=>'SECCION ALMACEN DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>11,'nomofic'=>'SECCION ADMISION FIJACION DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>12,'nomofic'=>'SECCION ESTADISTICAS DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>13,'nomofic'=>'SECCION ACTIVOS FIJOS DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>14,'nomofic'=>'SECCION CAJAS DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>15,'nomofic'=>'SECCION SERVICIOS GENERALES DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>28,'codofic'=>16,'nomofic'=>'DIVISION JEFATURA MEDICA DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>29,'codofic'=>17,'nomofic'=>'COMITÉ DE ASESOR Y GEST DE CALIDAD DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>29,'codofic'=>18,'nomofic'=>'MEDICINA GRAL Y ESPECIALIDADES MEDICAS DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>19,'nomofic'=>'SERVICIO DE DIAGNOSTICO Y TRATAMIENTO DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>20,'nomofic'=>'FISIOTERAPIA DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>21,'nomofic'=>'LABORATORIO DE ANALISIS CLINICO DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>22,'nomofic'=>'RAYOS X DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>23,'nomofic'=>'SERVICIO DE ODONTOLOGIA DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>24,'nomofic'=>'GABINETE MEDICOS DE TRANSITO DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSCBA','idestablecimiento'=>27,'codofic'=>25,'nomofic'=>'SERVICIO DE ENFERMERIA DEPTAL COCHABAMBA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>1,'nomofic'=>'DIRECCION DEPTAL DE SALUD Y BIENESTAR SOCIAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>2,'nomofic'=>'SECRETARIA DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>3,'nomofic'=>'UNIDAD JURIDICA DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>4,'nomofic'=>'TRABAJO SOCIAL DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>5,'nomofic'=>'PSICOLOGIA DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>6,'nomofic'=>'DIVISION DE PERSONAL DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>7,'nomofic'=>'MOVIMIENTO DE PERSONAL DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>8,'nomofic'=>'ESTADISTICAS Y ARCHIVO DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>9,'nomofic'=>'DIVISION ADMINISTRATIVA DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>10,'nomofic'=>'SECCION ALMACEN DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>11,'nomofic'=>'SECCION ADMISION FIJACION DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>12,'nomofic'=>'SECCION ESTADISTICAS DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>13,'nomofic'=>'SECCION ACTIVOS FIJOS DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>14,'nomofic'=>'SECCION CAJAS DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>15,'nomofic'=>'SECCION SERVICIOS GENERALES DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>16,'nomofic'=>'DIVISION JEFATURA MEDICA DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>17,'nomofic'=>'COMITÉ DE ASESOR Y GEST DE CALIDAD DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>18,'nomofic'=>'MEDICINA GRAL Y ESPECIALIDADES MEDICAS DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>19,'nomofic'=>'SERVICIO DE DIAGNOSTICO Y TRATAMIENTO DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>20,'nomofic'=>'FISIOTERAPIA DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>21,'nomofic'=>'LABORATORIO DE ANALISIS CLINICO DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>22,'nomofic'=>'RAYOS X DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>23,'nomofic'=>'SERVICIO DE ODONTOLOGIA DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>24,'nomofic'=>'GABINETE MEDICOS DE TRANSITO DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSUC','idestablecimiento'=>30,'codofic'=>25,'nomofic'=>'SERVICIO DE ENFERMERIA DEPTAL SUCRE','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>1,'nomofic'=>'DIRECCION DEPTAL DE SALUD Y BIENESTAR SOCIAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>2,'nomofic'=>'SECRETARIA DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>3,'nomofic'=>'UNIDAD JURIDICA DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>4,'nomofic'=>'TRABAJO SOCIAL DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>5,'nomofic'=>'PSICOLOGIA DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>6,'nomofic'=>'DIVISION DE PERSONAL DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>7,'nomofic'=>'MOVIMIENTO DE PERSONAL DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>8,'nomofic'=>'ESTADISTICAS Y ARCHIVO DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>9,'nomofic'=>'DIVISION ADMINISTRATIVA DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>10,'nomofic'=>'SECCION ALMACEN DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>11,'nomofic'=>'SECCION ADMISION FIJACION DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>12,'nomofic'=>'SECCION ESTADISTICAS DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>13,'nomofic'=>'SECCION ACTIVOS FIJOS DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>14,'nomofic'=>'SECCION CAJAS DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>15,'nomofic'=>'SECCION SERVICIOS GENERALES DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>16,'nomofic'=>'DIVISION JEFATURA MEDICA DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>17,'nomofic'=>'COMITÉ DE ASESOR Y GEST DE CALIDAD DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>18,'nomofic'=>'MEDICINA GRAL Y ESPECIALIDADES MEDICAS DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>19,'nomofic'=>'SERVICIO DE DIAGNOSTICO Y TRATAMIENTO DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>20,'nomofic'=>'FISIOTERAPIA DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>21,'nomofic'=>'LABORATORIO DE ANALISIS CLINICO DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>22,'nomofic'=>'RAYOS X DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>23,'nomofic'=>'SERVICIO DE ODONTOLOGIA DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>24,'nomofic'=>'GABINETE MEDICOS DE TRANSITO DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSTAR','idestablecimiento'=>33,'codofic'=>25,'nomofic'=>'SERVICIO DE ENFERMERIA DEPTAL TARIJA','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>1,'nomofic'=>'DIRECCION DEPTAL DE SALUD Y BIENESTAR SOCIAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>2,'nomofic'=>'SECRETARIA DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>3,'nomofic'=>'UNIDAD JURIDICA DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>4,'nomofic'=>'TRABAJO SOCIAL DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>5,'nomofic'=>'PSICOLOGIA DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>6,'nomofic'=>'DIVISION DE PERSONAL DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>7,'nomofic'=>'MOVIMIENTO DE PERSONAL DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>8,'nomofic'=>'ESTADISTICAS Y ARCHIVO DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>9,'nomofic'=>'DIVISION ADMINISTRATIVA DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>10,'nomofic'=>'SECCION ALMACEN DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>11,'nomofic'=>'SECCION ADMISION FIJACION DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>12,'nomofic'=>'SECCION ESTADISTICAS DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>13,'nomofic'=>'SECCION ACTIVOS FIJOS DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>14,'nomofic'=>'SECCION CAJAS DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>15,'nomofic'=>'SECCION SERVICIOS GENERALES DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>16,'nomofic'=>'DIVISION JEFATURA MEDICA DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>17,'nomofic'=>'COMITÉ DE ASESOR Y GEST DE CALIDAD DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>18,'nomofic'=>'MEDICINA GRAL Y ESPECIALIDADES MEDICAS DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>19,'nomofic'=>'SERVICIO DE DIAGNOSTICO Y TRATAMIENTO DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>20,'nomofic'=>'FISIOTERAPIA DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>21,'nomofic'=>'LABORATORIO DE ANALISIS CLINICO DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>22,'nomofic'=>'RAYOS X DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>23,'nomofic'=>'SERVICIO DE ODONTOLOGIA DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>24,'nomofic'=>'GABINETE MEDICOS DE TRANSITO DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSPAN','idestablecimiento'=>35,'codofic'=>25,'nomofic'=>'SERVICIO DE ENFERMERIA DEPTAL PANDO','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>1,'nomofic'=>'DIRECCION DEPTAL DE SALUD Y BIENESTAR SOCIAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>2,'nomofic'=>'SECRETARIA DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>3,'nomofic'=>'UNIDAD JURIDICA DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>4,'nomofic'=>'TRABAJO SOCIAL DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>5,'nomofic'=>'PSICOLOGIA DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>6,'nomofic'=>'DIVISION DE PERSONAL DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>7,'nomofic'=>'MOVIMIENTO DE PERSONAL DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>8,'nomofic'=>'ESTADISTICAS Y ARCHIVO DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>9,'nomofic'=>'DIVISION ADMINISTRATIVA DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>10,'nomofic'=>'SECCION ALMACEN DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>11,'nomofic'=>'SECCION ADMISION FIJACION DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>12,'nomofic'=>'SECCION ESTADISTICAS DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>13,'nomofic'=>'SECCION ACTIVOS FIJOS DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>14,'nomofic'=>'SECCION CAJAS DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>15,'nomofic'=>'SECCION SERVICIOS GENERALES DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>16,'nomofic'=>'DIVISION JEFATURA MEDICA DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>17,'nomofic'=>'COMITÉ DE ASESOR Y GEST DE CALIDAD DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>18,'nomofic'=>'MEDICINA GRAL Y ESPECIALIDADES MEDICAS DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>19,'nomofic'=>'SERVICIO DE DIAGNOSTICO Y TRATAMIENTO DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>20,'nomofic'=>'FISIOTERAPIA DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>21,'nomofic'=>'LABORATORIO DE ANALISIS CLINICO DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>22,'nomofic'=>'RAYOS X DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>23,'nomofic'=>'SERVICIO DE ODONTOLOGIA DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>24,'nomofic'=>'GABINETE MEDICOS DE TRANSITO DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSBEN','idestablecimiento'=>34,'codofic'=>25,'nomofic'=>'SERVICIO DE ENFERMERIA DEPTAL BENI','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>1,'nomofic'=>'DIRECCION DEPTAL DE SALUD Y BIENESTAR SOCIAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>2,'nomofic'=>'SECRETARIA DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>3,'nomofic'=>'UNIDAD JURIDICA DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>4,'nomofic'=>'TRABAJO SOCIAL DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>5,'nomofic'=>'PSICOLOGIA DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>6,'nomofic'=>'DIVISION DE PERSONAL DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>7,'nomofic'=>'MOVIMIENTO DE PERSONAL DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>8,'nomofic'=>'ESTADISTICAS Y ARCHIVO DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>9,'nomofic'=>'DIVISION ADMINISTRATIVA DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>10,'nomofic'=>'SECCION ALMACEN DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>11,'nomofic'=>'SECCION ADMISION FIJACION DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>12,'nomofic'=>'SECCION ESTADISTICAS DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>13,'nomofic'=>'SECCION ACTIVOS FIJOS DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>14,'nomofic'=>'SECCION CAJAS DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>15,'nomofic'=>'SECCION SERVICIOS GENERALES DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>16,'nomofic'=>'DIVISION JEFATURA MEDICA DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>17,'nomofic'=>'COMITÉ DE ASESOR Y GEST DE CALIDAD DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>18,'nomofic'=>'MEDICINA GRAL Y ESPECIALIDADES MEDICAS DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>19,'nomofic'=>'SERVICIO DE DIAGNOSTICO Y TRATAMIENTO DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>20,'nomofic'=>'FISIOTERAPIA DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>21,'nomofic'=>'LABORATORIO DE ANALISIS CLINICO DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>22,'nomofic'=>'RAYOS X DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>23,'nomofic'=>'SERVICIO DE ODONTOLOGIA DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>24,'nomofic'=>'GABINETE MEDICOS DE TRANSITO DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));
DB::table('oficina')->insert(array('entidad'=>'0015','unidad'=>'DSSCZ','idestablecimiento'=>24,'codofic'=>25,'nomofic'=>'SERVICIO DE ENFERMERIA DEPTAL SANTA CRUZ','feult'=>'18/12/2022','usuar'=>'admin','api_estado'=>1));

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('oficina');
    }
};
